// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dlqMetadata.proto

/*
Package dlqMetadata is a generated protocol buffer package.

It is generated from these files:
	dlqMetadata.proto

It has these top-level messages:

	DlqMetadata
*/
package consumer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DlqMetadata struct {
	RetryCount   int64  `protobuf:"varint,1,opt,name=retryCount" json:"retryCount,omitempty"`
	Topic        string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	Partition    int32  `protobuf:"varint,3,opt,name=partition" json:"partition,omitempty"`
	Offset       int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	TimestampSec int64  `protobuf:"varint,5,opt,name=timestamp_sec,json=timestampSec" json:"timestamp_sec,omitempty"`
	Data         []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DlqMetadata) Reset()                    { *m = DlqMetadata{} }
func (m *DlqMetadata) String() string            { return proto.CompactTextString(m) }
func (*DlqMetadata) ProtoMessage()               {}
func (*DlqMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DlqMetadata) GetRetryCount() int64 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *DlqMetadata) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *DlqMetadata) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *DlqMetadata) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DlqMetadata) GetTimestampSec() int64 {
	if m != nil {
		return m.TimestampSec
	}
	return 0
}

func (m *DlqMetadata) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DlqMetadata)(nil), "dlqMetadata")
}

func init() { proto.RegisterFile("dlqMetadata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xbf, 0x0a, 0xc2, 0x30,
	0x10, 0x06, 0x70, 0x62, 0xff, 0x40, 0xcf, 0x3a, 0x78, 0x88, 0x64, 0x10, 0x09, 0xba, 0x64, 0x72,
	0xf1, 0x11, 0x9c, 0x5d, 0xe2, 0x03, 0x48, 0x6c, 0x53, 0x08, 0xd8, 0x26, 0x26, 0xe7, 0xe0, 0x6b,
	0xf9, 0x84, 0x62, 0x14, 0xed, 0x76, 0xdf, 0xef, 0xe0, 0xe3, 0x83, 0x79, 0x7b, 0xbd, 0x1d, 0x0d,
	0xe9, 0x56, 0x93, 0xde, 0xf9, 0xe0, 0xc8, 0x6d, 0x9e, 0x0c, 0xa6, 0x23, 0xc5, 0x35, 0x40, 0x30,
	0x14, 0x1e, 0x07, 0x77, 0x1f, 0x88, 0x33, 0xc1, 0x64, 0xa6, 0x46, 0x82, 0x0b, 0x28, 0xc8, 0x79,
	0xdb, 0xf0, 0x89, 0x60, 0xb2, 0x52, 0x9f, 0x80, 0x2b, 0xa8, 0xbc, 0x0e, 0x64, 0xc9, 0xba, 0x81,
	0x67, 0x82, 0xc9, 0x42, 0xfd, 0x01, 0x97, 0x50, 0xba, 0xae, 0x8b, 0x86, 0x78, 0x9e, 0xfa, 0xbe,
	0x09, 0xb7, 0x30, 0x23, 0xdb, 0x9b, 0x48, 0xba, 0xf7, 0xe7, 0x68, 0x1a, 0x5e, 0xa4, 0x77, 0xfd,
	0xc3, 0x93, 0x69, 0x10, 0x21, 0x7f, 0x0f, 0xe3, 0xa5, 0x60, 0xb2, 0x56, 0xe9, 0xbe, 0x94, 0x69,
	0xfb, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xa1, 0xba, 0xbc, 0xd0, 0x00, 0x00, 0x00,
}
