// Code generated by github.com/alanctgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     dlq-metadata.avsc
 */

package avro

import (
	"io"
)

type DlqMetadata struct {
	RetryCount   int64
	Data         []byte
	Topic        string
	Partition    int64
	Offset       int64
	TimestampSec int64
}

func DeserializeDlqMetadata(r io.Reader) (*DlqMetadata, error) {
	return readDlqMetadata(r)
}

func NewDlqMetadata() *DlqMetadata {
	v := &DlqMetadata{}

	return v
}

func (r *DlqMetadata) Schema() string {
	return "{\"fields\":[{\"name\":\"retryCount\",\"type\":\"long\"},{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"topic\",\"type\":\"string\"},{\"name\":\"partition\",\"type\":\"long\"},{\"name\":\"offset\",\"type\":\"long\"},{\"name\":\"timestampSec\",\"type\":\"long\"}],\"name\":\"dlqMetadata\",\"namespace\":\"com.uber.kafka.dlq\",\"type\":\"record\"}"
}

func (r *DlqMetadata) Serialize(w io.Writer) error {
	return writeDlqMetadata(r, w)
}
